#!/bin/bash
# Get the C file name from the environment variable
CFILE=$CFILE
# Create the output file name by replacing .c with .s
OUTPUT_FILE=${CFILE%.c}.s
# Compile the C code to generate the assembly code in Intel syntax
gcc -S -masm=intel $CFILE -o $OUTPUT_FILE

